# Generated by Django 6.0.7 on 2026-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
